pipeline {
	agent any
	trigger {
		cron{'0 * * * *'}
	}
	stages {
		stage("Build") {
			steps {
				sh "dotnet build UsedProductExchangeSolution/UsedProductExchangeSolution.sln"
			}
		}
		stage("Test"){
			steps {
				sh "dotnet test UsedProductExchangeSolution/UsedProductExchange.XUnitTestProject"
			}
		}
	}
}
