pipeline {
	agent any
	trigger {
		cron("* */1 * * *") //Make it build every hour
	}
	stages {
		stage("Build") {
			steps {
				sh "dotnet build UsedProductExchangeSolution/UsedProductExchangeSolution.sln"
			}
		}
		stage("Test"){
			steps {
				sh "dotnet test UsedProductExchangeSolution/UsedProductExchangeSolution.sln"
			}
		}
	}
}
